<a href="https://colab.research.google.com/github/DaanMoura/AprendizadoDeMaquina/blob/main/AM1_SpotifyData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aprendizado de MÃ¡quina 1 - Trabalho 1

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
spotify = pd.read_csv("https://raw.githubusercontent.com/DaanMoura/AprendizadoDeMaquina/main/data/data.csv")

spotify.head()

   valence  year  acousticness  ... release_date  speechiness    tempo
0   0.0594  1921         0.982  ...         1921       0.0366   80.954
1   0.9630  1921         0.732  ...         1921       0.4150   60.936
2   0.0394  1921         0.961  ...         1921       0.0339  110.339
3   0.1650  1921         0.967  ...         1921       0.0354  100.109
4   0.2530  1921         0.957  ...         1921       0.0380  101.665

[5 rows x 19 columns]

In [2]:
spotify.describe()

             valence           year  ...    speechiness          tempo
count  170653.000000  170653.000000  ...  170653.000000  170653.000000
mean        0.528587    1976.787241  ...       0.098393     116.861590
std         0.263171      25.917853  ...       0.162740      30.708533
min         0.000000    1921.000000  ...       0.000000       0.000000
25%         0.317000    1956.000000  ...       0.034900      93.421000
50%         0.540000    1977.000000  ...       0.045000     114.729000
75%         0.747000    1999.000000  ...       0.075600     135.537000
max         1.000000    2020.000000  ...       0.970000     243.507000

[8 rows x 15 columns]